---
- name: include vars
  include_vars: main.yml

- name: install policycoreutils-python
  yum:
    name: policycoreutils-python

- name: install service
  yum:
    name: vsftpd
    state: latest

- name: set SELinux ftpd_anon_write boolean
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes

- name: open default ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ default_ports }}"

- name: backup vftpd config
  copy:
    src: /etc/vsftpd/vsftpd.conf
    remote_src: yes
    dest: /etc/vsftpd/vsftpd.conf.orig
    backup: yes

- name: open passive ports if enabled
  firewalld:
    port: "{{ passiv_ports }}"
    permanent: yes
    state: enabled
  when: open_passiv_ports

- name: Create anon_root directory
  file:
    path: "{{ anon_root }}"
    state: directory
    owner: ftp
    group: ftp
    mode: '555'

- name: Create pub directory
  file:
    path: "{{ pub_directory }}"
    state: directory
    owner: ftp
    group: ftp
    mode: '777'

- name: template a conf file to default dest
  template:  
    src: vsftpd.conf.j2
    dest:  /etc/vsftpd/vsftpd.conf
    force: yes
  notify: restart vsftpd

- name: start and enable service
  service:
    name: vsftpd
    state: started
    enabled: yes

- name: get facts
  service_facts:

- name: check service status
  debug:
    var: ansible_facts.services["httpd.service"]
